const data = [
  {
    name: "Sambousik",
    category: "Starters",
    unit: "Dozen",
    price: 4,
  },
  {
    name: "Kabkoub",
    category: "Starters",
    unit: "Dozen",
    price: 5,
  },
  {
    name: "Re2a2at Jebne",
    category: "Starters",
    unit: "Dozen",
    price: 4,
  },
  {
    name: "Re2a2at Jebne + Sojo2",
    category: "Starters",
    unit: "Dozen",
    price: 4,
  },
  {
    name: "Re2a2at Fajita",
    category: "Starters",
    unit: "Dozen",
    price: 5,
  },
  {
    name: "Spring Rolls",
    category: "Starters",
    unit: "Dozen",
    price: 3,
  },
  {
    name: "Pizza",
    category: "Starters",
    unit: "Dozen",
    price: 5,
  },
  {
    name: "Hot Dog",
    category: "Starters",
    unit: "Dozen",
    price: 5,
  },
  {
    name: "Lahem 3ajin",
    category: "Starters",
    unit: "Dozen",
    price: 4,
  },
  {
    name: "Crabe Salade",
    category: "Salade",
    unit: "4 Pers",
    price: 15,
  },
  {
    name: "Greek Salade",
    category: "Salade",
    unit: "4 Pers",
    price: 15,
  },
  {
    name: "Pasta Salade",
    category: "Salade",
    unit: "4 Pers",
    price: 15,
  },
  {
    name: "Tabbouleh",
    category: "Salade",
    unit: "4 Pers",
    price: 10,
  },
  {
    name: "Fattoush",
    category: "Salade",
    unit: "4 Pers",
    price: 10,
  },

  {
    name: "Wara2 3enab Zet",
    category: "Main Dishes",
    unit: "kg",
    price: 5,
  },
  {
    name: "Wara2 3enab Lahme",
    category: "Main Dishes",
    unit: "kg",
    price: 8,
  },
  {
    name: "Kroket",
    category: "Main Dishes",
    unit: "kg",
    price: 8,
  },
  {
    name: "Bajaxy",
    category: "Main Dishes",
    unit: "kg",
    price: 11,
  },
  {
    name: "Crispy",
    category: "Main Dishes",
    unit: "kg",
    price: 8,
  },
  {
    name: "Escalope",
    category: "Main Dishes",
    unit: "kg",
    price: 9,
  },
  {
    name: "Fajita",
    category: "Main Dishes",
    unit: "kg",
    price: 8,
  },
  {
    name: "Mahshe Sele2",
    category: "Main Dishes",
    unit: "kg",
    price: 4,
  },
  {
    name: "Mahshe Malfouf",
    category: "Main Dishes",
    unit: "kg",
    price: 7,
  },
  {
    name: "Shishbarak",
    category: "Main Dishes",
    unit: "100 pc",
    price: 4,
  },
  {
    name: "Shishbarak Kbir",
    category: "Main Dishes",
    unit: "100 pc",
    price: 4.5,
  },
  {
    name: "Kebbe Mamdoude",
    category: "Kebbe",
    unit: "kg",
    price: 8,
  },
  {
    name: "Kebbe Ma3 Basal w Loz",
    category: "Kebbe",
    unit: "kg",
    price: 9,
  },
  {
    name: "Eres kebbe Shahem",
    category: "Kebbe",
    unit: "pc",
    price: 2.5,
  },
  {
    name: "Eres kebbe Lahem",
    category: "Kebbe",
    unit: "pc",
    price: 3,
  },
  {
    name: "Salsa Harra",
    category: "Kebbe",
    unit: "kg",
    price: 3,
  },
  {
    name: "Zet Zaytoun",
    category: "Specials",
    unit: "1L",
    price: 5,
  },
  {
    name: "Apple Cider Vinegar",
    category: "Specials",
    unit: "1L",
    price: 3,
  },
  {
    name: "Add Sauce",
    category: "Specials",
    unit: "",
    price: 2,
  },
];
